baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Lumina Wiki Theme'
summaryLength = 10
paginate = 10

[taxonomies]
  tag = "tags"

[params]
dateFormat = "Jan 2, 2006"
yearStart = ""

[markup.goldmark.renderer]
unsafe= true


